# -*- coding: utf-8 -*-
"""blog_entry

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SbI-7RenH8kqYttAsM_MuTOWV4B7dT4V
"""

'''
Program: blog_entry.py. 

Programmer: Omar Shatrat

Date: 10/07/2022

Description: Blog entry program that summaries large text by returning first 10 words, masking characters, and returning counts of masked characters.

'''


def get_user_name():
  CHR = 2
  user_name = input('Enter username >= 2 characters: ')
  while len(user_name) < CHR:
    user_name = input('Please enter username >= 2 characters: ')
  return user_name

def get_text():
  MIN = 100
  MAX = 500
  text = input('Please enter a text >= 100 and <= 500 characters: ')
  while len(text) < 100 or len(text) > 500:
    text = input('Please enter a text or sentence >= 100 and <= 500 characters: ')
  return text

def get_key_character():
  KEY = 1
  chr = input('Please enter a SINGLE character to act as key: ')
  while len(chr) != KEY:
    chr = input('Please enter a SINGLE character to act as key: ')
  return chr

def first_ten_words(the_string):
  words = the_string.split(' ')
  return ' '.join(words[0:10])

def mask_character(the_string, key_character):
  return the_string.replace(key_character, '*')

def count_key(the_string, key_character):
  cnt = 0
  for i in the_string:
    if i == key_character:
      cnt += 1
  return cnt  

def main():
  user_name = get_user_name()
  key_character = get_key_character()
  the_text = get_text()
  
  text_summary = first_ten_words(the_text)
  print('\nThe first ten words of the blog_entry as a summary of the entry: \n')
  print(text_summary)

  new_string = mask_character(the_text, key_character)
  print("\nString with key character, " '\''+key_character+'\'', 'masked: \n')
  print(new_string)

  num_keys = count_key(the_text, key_character)
  print('\n# of occurrences of key character,', '\''+key_character+'\': ', num_keys)

main()

'''Sample run 1
Enter username >= 2 characters: H
Please enter username >= 2 characters: Hanan
Please enter a SINGLE character to act as key: sdfs
Please enter a SINGLE character to act as key: 
Please enter a SINGLE character to act as key: c
Please enter a text >= 100 and <= 500 characters: Whether computer science is one of your college courses or just something of casual interest.
Please enter a text or sentence >= 100 and <= 500 characters: Whether computer science is one of your college courses or just something of casual interest, this blog post is dedicated to you. Detailing 30 of the best computer science blogs, this list is a place to start; continue your own education and find enriching, intriguing topics related to this rapidly changing discipline, no matter your level of experience or your background.

The first ten words of the blog_entry as a summary of the entry: 

Whether computer science is one of your college courses or

String with key character, 'c' masked: 

Whether *omputer s*ien*e is one of your *ollege *ourses or just something of *asual interest, this blog post is dedi*ated to you. Detailing 30 of the best *omputer s*ien*e blogs, this list is a pla*e to start; *ontinue your own edu*ation and find enri*hing, intriguing topi*s related to this rapidly *hanging dis*ipline, no matter your level of experien*e or your ba*kground.

# of occurrences of key character, 'c':  19
'''

'''Sample run 2
Enter username >= 2 characters: OS
Please enter a SINGLE character to act as key: c
Please enter a text >= 100 and <= 500 characters: Whether computer science is one of your college courses or just something of casual interest, this blog post is dedicated to you. Detailing 30 of the best computer science blogs, this list is a place to start; continue your own education and find enriching, intriguing topics related to this rapidly changing discipline, no matter your level of experience or your background.

The first ten words of the blog_entry as a summary of the entry: 

Whether computer science is one of your college courses or

String with key character, 'c' masked: 

Whether *omputer s*ien*e is one of your *ollege *ourses or just something of *asual interest, this blog post is dedi*ated to you. Detailing 30 of the best *omputer s*ien*e blogs, this list is a pla*e to start; *ontinue your own edu*ation and find enri*hing, intriguing topi*s related to this rapidly *hanging dis*ipline, no matter your level of experien*e or your ba*kground.

# of occurrences of key character, 'c':  19
'''