# -*- coding: utf-8 -*-
"""computer_assisted.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MZo7ojlp0tHMb0colreeJBvhbDpjLRqY
"""

'''
Program:computer_assisted.py. 

Programmer: Omar Shatrat

Date: 09/25/2022

Description: Computer-assisted instruction (CAI) refers to the use of computers in education. Write a program to help an elementary school student learn multiplication, division, addition, and subtraction.

'''
#Defines menu options
ADDITION = 1 #Constant menu choice for addition
SUBTRACTION = 2 #Constant menu choice for subtraction
MULTIPLICATION = 3 #Constant menu choice for multiplication
DIVISION = 4 #Constant menu choice for division

#Prints menu to user
operation = int(input("1 = addition \n2 = subtraction \n3 = multiplication \n4 = division \nEnter the operation (1 to 4) or -1 to exit: ")) #Menu options

#Declares values that will be used in computation
rand1 = 8 #Randomly generated value 1
rand2 = 2 #Randomly generated value 2

#Depending on choice from menu, the operation is performed. If the answer is correct, the loop concludes. If it is incorrect, the user is prompted until they are correct. 
if operation == 1:
  print('How much is', rand1, '+', str(rand2)+'?')
  answer = int(input('Enter your answer: ')) #Input variable taking menu choice, repeate throughout code
  while answer != rand1+rand2:
    print("Incorrect, please try again!")
    answer = int(input('Enter your answer: '))
  print('Correct, good work!')
elif operation == 2:
  print('How much is', rand1, '-', str(rand2)+'?')
  answer = int(input('Enter your answer: '))
  while answer != rand1-rand2:
    print("Incorrect, please try again!")
    answer = int(input('Enter your answer: '))
  print('Correct, good work!')
elif operation == 3:
  print('How much is', rand1, '*', str(rand2)+'?')
  answer = int(input('Enter your answer: '))
  while answer != rand1*rand2:
    print("Incorrect, please try again!")
    answer = int(input('Enter your answer: '))
  print('Correct, good work!')
elif operation == 4:
  print('How much is', rand1, '/', str(rand2)+'?')
  answer = int(input('Enter your answer: '))
  while answer != rand1/rand2:
    print("Incorrect, please try again!")
    answer = int(input('Enter your answer: '))
  print('Correct, good work!')
elif operation == -1:
  print("Thanks for playing!")

'''Sample runs
1 = addition 
2 = subtraction 
3 = multiplication 
4 = division 
Enter the operation (1 to 4) or -1 to exit: 1
How much is 8 + 2?
Enter your answer: 2
Incorrect, please try again!
Enter your answer: 10
Correct, good work!

1 = addition 
2 = subtraction 
3 = multiplication 
4 = division 
Enter the operation (1 to 4) or -1 to exit: 2
How much is 8 - 2?
Enter your answer: 3
Incorrect, please try again!
Enter your answer: 6
Correct, good work!

1 = addition 
2 = subtraction 
3 = multiplication 
4 = division 
Enter the operation (1 to 4) or -1 to exit: 3
How much is 8 * 2?
Enter your answer: 4
Incorrect, please try again!
Enter your answer: 16
Correct, good work!

1 = addition 
2 = subtraction 
3 = multiplication 
4 = division 
Enter the operation (1 to 4) or -1 to exit: 4
How much is 8 / 2?
Enter your answer: 3
Incorrect, please try again!
Enter your answer: 2
Incorrect, please try again!
Enter your answer: 4
Correct, good work!

1 = addition 
2 = subtraction 
3 = multiplication 
4 = division 
Enter the operation (1 to 4) or -1 to exit: -1
Thanks for playing!
'''